In [15]:
k=[4,2.56789,9,87.9999,40]
k


[4, 2.56789, 9, 87.9999, 40]

In [12]:
import pandas as pd
import numpy as np
import seaborn as sns


In [16]:
pd.Series(k)

0     4.00000
1     2.56789
2     9.00000
3    87.99990
4    40.00000
dtype: float64

In [23]:
a=np.random.randint(20,50,15)

In [24]:
a

array([40, 36, 30, 28, 23, 31, 36, 42, 39, 36, 34, 48, 47, 38, 30])

In [25]:
a.ndim

1

In [26]:
pd.Series(a)

0     40
1     36
2     30
3     28
4     23
5     31
6     36
7     42
8     39
9     36
10    34
11    48
12    47
13    38
14    30
dtype: int32

In [36]:
np.random.seed(34)
b=np.random.randint(100,200,(6,5))
b

array([[133, 185, 168, 135, 169],
       [111, 178, 129, 118, 129],
       [189, 129, 120, 196, 162],
       [105, 120, 151, 119, 185],
       [121, 163, 172, 142, 184],
       [172, 177, 136, 102, 137]])

In [37]:
b.ndim

2

In [38]:
b

array([[133, 185, 168, 135, 169],
       [111, 178, 129, 118, 129],
       [189, 129, 120, 196, 162],
       [105, 120, 151, 119, 185],
       [121, 163, 172, 142, 184],
       [172, 177, 136, 102, 137]])

In [44]:
df=pd.DataFrame(b,columns=['Roll','name','age','adds','country'],index=[182,183,185,186,187,187])
df

Roll  name  age  adds  country
182   133   185  168   135      169
183   111   178  129   118      129
185   189   129  120   196      162
186   105   120  151   119      185
187   121   163  172   142      184
187   172   177  136   102      137

In [45]:
df.loc[182]

Roll       133
name       185
age        168
adds       135
country    169
Name: 182, dtype: int32

In [46]:
df.iloc[0]

Roll       133
name       185
age        168
adds       135
country    169
Name: 182, dtype: int32

In [47]:
df.iloc[[2,4]]

Roll  name  age  adds  country
185   189   129  120   196      162
187   121   163  172   142      184

In [50]:
df.loc[[182,185]]

Roll  name  age  adds  country
182   133   185  168   135      169
185   189   129  120   196      162

In [51]:
df['age']

182    168
183    129
185    120
186    151
187    172
187    136
Name: age, dtype: int32

In [52]:
df[['age','name']]

age  name
182  168   185
183  129   178
185  120   129
186  151   120
187  172   163
187  136   177

In [53]:
df.loc[[182,185,186],['adds','name','age']]

adds  name  age
182   135   185  168
185   196   129  120
186   119   120  151

In [54]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic',
 'anagrams',
 'anagrams',
 'anscombe',
 'anscombe',
 'attention',
 'attention',
 'brain_networks',
 'brain_networks',
 'car_crashes',
 'car_crashes',
 'diamonds',
 'diamonds',
 'dots',
 'dots',
 'dowjones',
 'dowjones',
 'exercise',
 'exercise',
 'flights',
 'flights',
 'fmri',
 'fmri',
 'geyser',
 'geyser',
 'glue',
 'glue',
 'healthexp',
 'healthexp',
 'iris',
 'iris',
 'mpg',
 'mpg',
 'penguins',
 'penguins',
 'planets',
 'planets',
 'seaice',
 'seaice',
 'taxis',
 'taxis',
 'tips',
 'tips',
 'titanic',
 'titanic',
 'anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'plan

In [56]:
df=sns.load_dataset('diamonds')
df

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [57]:
type(df)

pandas.core.frame.DataFrame

In [58]:
df.shape

(53940, 10)

In [60]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')