In [20]:
from pandas import read_csv
import seaborn as sns
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2,f_regression
dataframe=sns.load_dataset('tips')
dataframe

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [21]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
dataframe['smoker']=lb.fit_transform(dataframe['smoker'])
dataframe['sex']=lb.fit_transform(dataframe['sex'])
dataframe['time']=lb.fit_transform(dataframe['time'])
dataframe['day']=lb.fit_transform(dataframe['day'])

In [22]:
X = dataframe.iloc[:,1:]
Y = dataframe.iloc[:,0]

In [24]:
X

tip  sex  smoker  day  time  size
0    1.01    0       0    2     0     2
1    1.66    1       0    2     0     3
2    3.50    1       0    2     0     3
3    3.31    1       0    2     0     2
4    3.61    0       0    2     0     4
..    ...  ...     ...  ...   ...   ...
239  5.92    1       0    1     0     3
240  2.00    0       1    1     0     2
241  2.00    1       1    1     0     2
242  1.75    1       0    1     0     2
243  3.00    0       0    3     0     2

[244 rows x 6 columns]

In [25]:
X = dataframe.drop('tip',axis=1)
Y = dataframe.tip

In [6]:
X

total_bill  sex  smoker  day  time  size
0         16.99    0       0    2     0     2
1         10.34    1       0    2     0     3
2         21.01    1       0    2     0     3
3         23.68    1       0    2     0     2
4         24.59    0       0    2     0     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       0    1     0     3
240       27.18    0       1    1     0     2
241       22.67    1       1    1     0     2
242       17.82    1       0    1     0     2
243       18.78    0       0    3     0     2

[244 rows x 6 columns]

In [7]:
test = SelectKBest(score_func=f_regression, k=3).fit(X,Y)
test

SelectKBest(k=3, score_func=<function f_regression at 0x0000018E1EC004A0>)

In [8]:
np.round(test.scores_,2)

array([2.0336e+02, 1.9300e+00, 1.0000e-02, 3.0000e-02, 3.6300e+00,
       7.6180e+01])

In [9]:
np.round(test.pvalues_,3)

array([0.   , 0.166, 0.927, 0.858, 0.058, 0.   ])

In [10]:
dataframe.columns[test.get_support(indices=True)]

Index(['total_bill', 'day', 'time'], dtype='object')

In [11]:
dataframe.columns[np.where(test.pvalues_>0.05)]

Index(['tip', 'sex', 'smoker', 'day'], dtype='object')

In [12]:
df=sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [13]:
x=df.iloc[:,0:4]
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [14]:
y=df['species']

In [26]:
sel=SelectKBest(score_func=chi2,k=2).fit(x,y)
sel

SelectKBest(k=2, score_func=<function chi2 at 0x0000018E1EC00220>)

In [27]:
sel.pvalues_

array([4.47651499e-03, 1.56395980e-01, 5.53397228e-26, 2.75824965e-15])

In [28]:
sel.scores_

array([ 10.81782088,   3.7107283 , 116.31261309,  67.0483602 ])

In [29]:
sel.get_support(indices=True)

array([2, 3], dtype=int64)

In [31]:
df.columns[np.where(sel.get_support(indices=True))]

Index(['sepal_length', 'sepal_width'], dtype='object')

In [32]:
import pandas as pd
data = pd.read_csv(r"C:\Users\kathy\Downloads\NewspaperData.csv")
data.head()

Newspaper    daily   sunday
0       Baltimore Sun  391.952  488.506
1        Boston Globe  516.981  798.298
2       Boston Herald  355.628  235.084
3  Charlotte Observer  238.555  299.451
4   Chicago Sun Times  537.780  559.093

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Newspaper  34 non-null     object 
 1   daily      34 non-null     float64
 2   sunday     34 non-null     float64
dtypes: float64(2), object(1)
memory usage: 948.0+ bytes


In [35]:
data.sample()

Newspaper    daily   sunday
19   Newsday  825.512  960.308

In [36]:
data.tail()

Newspaper    daily    sunday
29  San Francisco Chronicle  570.364   704.322
30  St. Louis Post-Dispatch  391.286   585.681
31   St. Paul Pioneer Press  201.860   267.781
32            Tampa Tribune  321.626   408.343
33          Washington Post  838.902  1165.567

In [41]:
data.shape 

(34, 3)

In [42]:
data.drop('Newspaper',axis=1).corr()

daily    sunday
daily   1.000000  0.958154
sunday  0.958154  1.000000